In [ ]:
import numpy as np

# Creating array using Numpy

In [ ]:
a = np.array([5,5,5])
food = np.array(['samosa', 'pakora'])
print(a)
food

In [ ]:
print(type(food))
type(a)

In [ ]:
print(len(food))
len(a)

In [ ]:
print(a[1:])
print(a.mean())

In [19]:
np.ones(4, dtype=np.float32)

array([1., 1., 1., 1.], dtype=float32)

In [24]:
np.arange(1,25,4,dtype=np.int64)

array([ 1,  5,  9, 13, 17, 21], dtype=int64)

# Array functions

In [26]:
a = np.array([1,3,.4,3]) #took everything as float
a

array([1. , 3. , 0.4, 3. ])

In [29]:
a.sort()
a

array([0.4, 1. , 3. , 3. ])

In [36]:
b = np.array([2,4,2,4,2,1])
b

array([2, 4, 2, 4, 2, 1])

In [41]:
c = np.concatenate((a,b))
c.sort()
c

array([0.4, 1. , 1. , 2. , 2. , 2. , 3. , 3. , 4. , 4. ])

# 2D Array

In [44]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
b= np.array([[1,2],[3,6]])
b

array([[1, 2],
       [3, 6]])

In [58]:
c = np.concatenate((a,b) , axis = 1)
print(c)
c.ndim

[[1 2 3 1 2]
 [4 5 6 3 6]]


2

In [59]:
c.shape

(2, 5)

In [66]:
a = np.arange(12).reshape((((6,2))))

In [79]:
np.reshape(a, newshape=(3,4),order='f')

array([[ 0,  6,  1,  7],
       [ 2,  8,  3,  9],
       [ 4, 10,  5, 11]])

In [82]:
z = np.array([1,2,3,4,5,6])
y = z[np.newaxis,:]
y

array([[1, 2, 3, 4, 5, 6]])

In [83]:
x = z[:,np.newaxis]
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [85]:
x.sum()

21

In [87]:
x+5

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [88]:
x.mean()

3.5